# Generated by Django 5.0.7 on 2024-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
